github: [theabbie]
patreon: theabbie
open_collective: theabbie
ko_fi: theabbie
tidelift: npm/theabbie
liberapay: theabbie
issuehunt: theabbie
otechie: theabbie
lfx_crowdfunding: 1dce55e1-361d-49b1-8d6e-63185ef61d02
custom: ['https://theabbie.github.io', 'https://paypal.me/theabbie','https://donorbox.org/theabbie']
